$schema: "http://json-schema.org/draft-04/schema#"
description: Snakemake configuration file
type: object

# Properties below need to be updated.
# # possible entries of the config file and which type they should be
# properties:

#   experiment_group_names:
#     type: dict
#     description: Keys contain the experimental sample group names, and a list of experiment_tagged_sets that form each group.

#   experiment_tagged_sets:
#     type: dict
#     description: Keys contain the experimental sample names, values specify the locations of the tagged sets for each sample.
    
#   simulation_folder:
#     type: string
#     description: Path to the root folder for simulations.
    
#   simulation_group_names:
#     type: dict
#     description: Keys contain the simulation group names, values are a list of simulations that combine to form the group.
    
#   Fbn2_simulation_parameters:
#     type: dict
#     description: Parameters used for retrieving the 3D monomer positions from a simulation and other information. 
    
#   contact_map_parameters:
#     type: dict
#     description: Information needed to generate contact maps from the simulation data.
    
# entries that have to be in the config file for successful validation
required:
  - experiment_group_names
  - experiment_tagged_sets
  - simulation_folder
  - simulation_group_names
  - DSB_simulation_parameters    
